resolutions = [512]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7

[[directory]]
path = '/home/bluvoll/anima-pain/0000/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0001/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0002/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0003/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0004/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0005/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0006/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0007/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0008/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0009/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0010/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0011/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0012/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0013/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0014/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0015/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0016/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0017/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0018/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0019/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0020/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0021/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0022/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0023/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0024/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0025/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0026/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0027/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0028/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0029/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0030/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0031/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0032/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0033/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0034/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0035/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0036/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0037/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0038/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0039/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0040/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0041/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0042/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0043/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0044/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0045/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0046/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0047/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0048/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0049/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0050/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0051/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0052/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0053/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0054/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0055/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0056/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0057/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0058/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0059/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0060/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0061/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0062/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0063/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0064/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0065/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0066/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0067/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0068/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0069/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0070/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0071/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0072/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0073/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0074/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0075/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0076/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0077/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0078/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0079/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0080/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0081/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0082/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0083/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0084/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0085/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0086/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0087/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0088/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0089/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0090/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0091/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0092/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0093/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0094/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0095/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0096/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0097/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0098/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0099/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0100/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0101/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0102/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0103/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0104/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0105/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0106/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0107/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0108/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0109/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0110/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0111/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0112/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0113/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0114/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0115/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0116/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0117/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0118/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0119/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0120/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0121/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0122/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0123/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0124/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0125/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0126/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0127/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0128/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0129/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0130/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0131/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0132/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0133/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0134/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0135/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0136/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0137/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0138/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0139/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0140/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0141/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0142/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0143/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0144/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0145/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0146/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0147/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0148/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0149/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0150/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0151/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0152/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0153/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0154/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0155/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0156/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0157/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0158/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0159/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0160/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0161/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0162/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0163/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0164/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0165/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0166/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0167/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0168/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0169/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0170/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0171/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0172/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0173/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0174/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0175/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0176/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0177/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0178/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0179/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0180/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0181/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0182/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0183/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0184/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0185/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0186/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0187/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0188/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0189/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0190/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0191/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0192/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0193/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0194/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0195/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0196/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0197/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0198/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0199/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0200/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0201/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0202/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0203/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0204/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0205/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0206/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0207/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0208/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0209/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0210/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0211/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0212/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0213/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0214/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0215/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0216/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0217/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0218/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0219/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0220/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0221/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0222/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0223/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0224/'
num_repeats = 1

[[directory]]
path = '/home/bluvoll/anima-pain/0225/'
num_repeats = 1
